// SPDX-FileCopyrightText: Copyright Orangebot, Inc. and Medplum contributors
// SPDX-License-Identifier: Apache-2.0

export type QueueStage = 'CHECKIN' | 'TRIAGE' | 'CONSULT' | 'BILLING' | 'DISCHARGED';

export interface QueuePatientItem {
  id: string;
  name: string;
  age: number;
  gender: 'M' | 'F';
  dob: string;
  time: string;
  waitMinutes: string;
  stage: QueueStage;
  stageLabel: string;
  doctor: string;
  priority: 'Standard' | 'Senior Priority' | 'PWD Priority';
  senior: boolean;
  pwd: boolean;
  targetTab: 'soap' | 'vitals' | 'rx' | 'history' | 'billing';
  chiefComplaint: string;
  branchId: string;
}

// Initial branch-segregated queue datasets (strictly isolated contents per clinic facility)
export const INITIAL_BRANCH_QUEUES: Record<string, QueuePatientItem[]> = {
  'branch-espinosa': [
    {
      id: 'pat-102',
      name: 'Maria Angelica Santos',
      age: 34,
      gender: 'F',
      dob: '1992-08-25',
      time: '01:15 PM',
      waitMinutes: '12m',
      stage: 'CONSULT',
      stageLabel: 'With Attending Doctor',
      doctor: 'Dr. Florence Espinosa, MD',
      priority: 'Standard',
      senior: false,
      pwd: false,
      targetTab: 'soap',
      chiefComplaint: '28 weeks AOG Antenatal Checkup & Pelvic Ultrasound review',
      branchId: 'branch-espinosa',
    },
    {
      id: 'pat-104',
      name: 'Kristine Joy Bernardo',
      age: 28,
      gender: 'F',
      dob: '1998-03-14',
      time: '01:40 PM',
      waitMinutes: '8m',
      stage: 'TRIAGE',
      stageLabel: 'Nurse Triage Vitals',
      doctor: 'Dr. Florence Espinosa, MD',
      priority: 'Standard',
      senior: false,
      pwd: false,
      targetTab: 'vitals',
      chiefComplaint: '1st Trimester Prenatal Routine Check & severe hyperemesis gravidarum',
      branchId: 'branch-espinosa',
    },
    {
      id: 'pat-106',
      name: 'Carmela Ramos',
      age: 61,
      gender: 'F',
      dob: '1965-02-18',
      time: '01:10 PM',
      waitMinutes: 'Completed',
      stage: 'BILLING',
      stageLabel: 'For Cashier Payment',
      doctor: 'Dr. Florence Espinosa, MD',
      priority: 'Senior Priority',
      senior: true,
      pwd: false,
      targetTab: 'billing',
      chiefComplaint: 'Post-menopausal routine Pap smear & hormone clearance',
      branchId: 'branch-espinosa',
    },
    {
      id: 'pat-105',
      name: 'Andrea Dizon',
      age: 42,
      gender: 'F',
      dob: '1984-06-30',
      time: '02:00 PM',
      waitMinutes: '5m',
      stage: 'CHECKIN',
      stageLabel: 'Front Desk Arrived',
      doctor: 'Dr. Florence Espinosa, MD',
      priority: 'Standard',
      senior: false,
      pwd: false,
      targetTab: 'soap',
      chiefComplaint: 'Dysfunctional Uterine Bleeding workup & Transvaginal Ultrasound',
      branchId: 'branch-espinosa',
    },
    {
      id: 'pat-107',
      name: 'Beatrice Mendoza',
      age: 25,
      gender: 'F',
      dob: '2001-11-10',
      time: '12:30 PM',
      waitMinutes: 'Discharged',
      stage: 'DISCHARGED',
      stageLabel: 'Discharged',
      doctor: 'Dr. Florence Espinosa, MD',
      priority: 'Standard',
      senior: false,
      pwd: false,
      targetTab: 'history',
      chiefComplaint: 'Pre-marital health counseling & Cervical Cancer HPV dose #1',
      branchId: 'branch-espinosa',
    },
  ],
  'branch-ulticare': [
    {
      id: 'pat-201',
      name: 'Rowena Bautista',
      age: 31,
      gender: 'F',
      dob: '1995-04-18',
      time: '09:30 AM',
      waitMinutes: '10m',
      stage: 'CONSULT',
      stageLabel: 'With Attending Doctor',
      doctor: 'Dr. Florence Espinosa, MD',
      priority: 'Standard',
      senior: false,
      pwd: false,
      targetTab: 'soap',
      chiefComplaint: '32-week Biophysical Profile (BPS) & Gestational Diabetes Mellitus',
      branchId: 'branch-ulticare',
    },
    {
      id: 'pat-202',
      name: 'Jennifer De Leon',
      age: 38,
      gender: 'F',
      dob: '1988-09-02',
      time: '10:00 AM',
      waitMinutes: '15m',
      stage: 'TRIAGE',
      stageLabel: 'Nurse Triage Vitals',
      doctor: 'Dr. Roberto Gomez, MD',
      priority: 'Standard',
      senior: false,
      pwd: false,
      targetTab: 'vitals',
      chiefComplaint: 'Pelvic pain & suspected ovarian cyst follow-up TVS',
      branchId: 'branch-ulticare',
    },
    {
      id: 'pat-203',
      name: 'Estrella Bautista',
      age: 69,
      gender: 'F',
      dob: '1957-09-14',
      time: '09:00 AM',
      waitMinutes: 'Completed',
      stage: 'BILLING',
      stageLabel: 'For Cashier Payment',
      doctor: 'Dr. Florence Espinosa, MD',
      priority: 'Senior Priority',
      senior: true,
      pwd: false,
      targetTab: 'billing',
      chiefComplaint: 'Senior Gynecological Wellness & Mammogram clearance',
      branchId: 'branch-ulticare',
    },
  ],
  'branch-ace': [
    {
      id: 'pat-301',
      name: 'Patricia Lim',
      age: 29,
      gender: 'F',
      dob: '1997-01-22',
      time: '10:15 AM',
      waitMinutes: '5m',
      stage: 'CONSULT',
      stageLabel: 'With Attending Doctor',
      doctor: 'Dr. Florence Espinosa, MD',
      priority: 'Standard',
      senior: false,
      pwd: false,
      targetTab: 'soap',
      chiefComplaint: '38-week scheduled Elective Repeat Cesarean Section pre-op consult',
      branchId: 'branch-ace',
    },
    {
      id: 'pat-302',
      name: 'Camille Villafuerte',
      age: 33,
      gender: 'F',
      dob: '1993-05-11',
      time: '10:45 AM',
      waitMinutes: '2m',
      stage: 'CHECKIN',
      stageLabel: 'Front Desk Arrived',
      doctor: 'Dr. Florence Espinosa, MD',
      priority: 'Standard',
      senior: false,
      pwd: false,
      targetTab: 'soap',
      chiefComplaint: 'Post-cesarean wound check & lactation counseling',
      branchId: 'branch-ace',
    },
  ],
};
